apiVersion: v1
kind: PersistentVolume
metadata:
  name: ebs-static-pv
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 20Gi
  csi:
    driver: ebs.csi.aws.com
    fsType: ext4
    volumeHandle: vol-0e220ec6b388ac396 # Replace with your EBS volume ID
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-static-pvc
spec:
  storageClassName: ""
  volumeName: ebs-static-pv
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: ebs-static-pod
  labels:
    purpose: ebs-static-pod
    app: nginx
spec:
  nodeSelector:
    topology.kubernetes.io/zone: us-east-1b # Replace with your zone
  containers:
  - name: ebs-container
    image: nginx
    volumeMounts:
    - mountPath: /usr/share/nginx/html
      name: ebs-static-pv
  volumes:
  - name: ebs-static-pv
    persistentVolumeClaim:
      claimName: ebs-static-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: ebs-static-service-loadbalancer
spec:
  type: LoadBalancer
  selector:
    purpose: ebs-static-pod
  ports:
  - name: nginx-svc-port
    protocol: TCP 
    port: 80
    targetPort: 80
    nodePort: 30080