apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-dynamic-pvc
spec:
  storageClassName: "expense-ebs" # Use the StorageClass created in 02-sc.yaml
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: ebs-dynamic-pod
  labels:
    purpose: ebs-dynamic-pod
    app: nginx
spec:
  nodeSelector:
    topology.kubernetes.io/zone: us-east-1b # Replace with your zone
  containers:
  - name: ebs-container
    image: nginx
    volumeMounts:
    - mountPath: /usr/share/nginx/html
      name: ebs-dynamic-pv
  volumes:
  - name: ebs-dynamic-pv
    persistentVolumeClaim:
      claimName: ebs-dynamic-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: ebs-dynamic-service-loadbalancer
spec:
  type: LoadBalancer
  selector:
    purpose: ebs-dynamic-pod
  ports:
  - name: nginx-svc-port
    protocol: TCP 
    port: 80
    targetPort: 80
    nodePort: 30080