apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-static-pv
spec:
  capacity:
    storage: 3Gi
  volumeMode: Filesystem
  storageClassName: "" # Use the StorageClass created in 02-sc.yaml
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-038925e9c2b13a920 # Replace with your EFS file system ID