apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: expense-efs-dynamic
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
  storageClassName: efs-sc # Use the StorageClass created in 05-efs-sc.yaml
---
apiVersion: v1
kind: Pod
metadata:
  name: efs-dynamic-pod
  labels:
    purpose: efs-dynamic-pod
    app: nginx
spec:
  nodeSelector:
    topology.kubernetes.io/zone: us-east-1b
  containers:
  - name: efs-container
    image: nginx    
    voulumeMounts:
    - name: expense-efs-dynamic
      mountPath: /usr/share/nginx/html
  volumes:
  - name: expense-efs-dynamic
    persistentVolumeClaim:
      claimName: expense-efs-dynamic
---
kind: Service
apiVersion: v1
metadata:
  name: efs-dynamic-service-loadbalancer
spec:
  type: LoadBalancer
  selector:
    purpose: efs-dynamic-pod
  ports:
  - name: nginx-svc-port
    protocol: TCP 
    port: 80
    containerPort: 80
    nodePort: 30080 # Optional, specify a node port if needed