apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  # docker run -d --name nginx nginx
  - name: nginx
    image: nginx:stable-perl
    
# kind: Pod
# apiVersion: v1
# metadata:
#   name: expense
#   spec:
#   containers:
#   - name: nginx-container
#     image: nginx:latest
#     ports:
#       - containerPort: 80