kind: Pod
apiVersion: v1
metadata:
  name: resource
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      requests:
       cpu: 68m
       memory: 100m
      limits:
        cpu: 100m
        memory: 120m