kind: Pod
apiVersion: v1
metadata:
  name: resource
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      requests:       
       cpu: 68mi
       memory: 100m
      limits:
        cpu: 100mi 
        memory: 120m