kind: Pod
apiVersion: v1
metadata:
  name: pod-secret
spec:
  containers:
  - name: nginx
    image: nginx
    envFrom:
    - secretRef:
        name: pod-secret
    # env:
    # - name: USERNAME
    #   valueFrom:
    #     secretKeyRef:
    #       name: pod-secret
    #       key: username
    # - name: PASSWORD
    #   valueFrom:
    #     secretKeyRef:
    #       name: pod-secret
    #       key: password